# Generated by Django 2.2.7 on 2019-12-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AddField(
            model_name='title',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
